# Generated by Django 2.1.2 on 2018-10-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_red_field', models.IntegerField()),
                ('text_green_field', models.IntegerField()),
                ('text_blue_field', models.IntegerField()),
            ],
        ),
    ]
